version: '3'

services:
  db:
    image: postgres:15
    container_name: financial-watchdog-backend-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgres_data:
